// Auto-generated by scripts/extract-map-data.py — do not edit manually.
// Re-run the script whenever the source data file is updated.
const MAP_DATA = {
  "sectors": [
    "Accommodation & Food Services",
    "Administrative & Support",
    "Agriculture, Forestry & Fishing",
    "Construction",
    "Energy & Water Supply",
    "Financial & Insurance",
    "Hospitality",
    "Information & Communication",
    "Manufacturing",
    "Mining & Quarrying",
    "Other Services",
    "Professional, Scientific & Tech",
    "Public Sector",
    "Real Estate",
    "Retail",
    "Transport & Storage",
    "Unknown / Foreign",
    "Wholesale & Retail Trade"
  ],
  "centroids": {
    "AB": [
      57.149,
      -2.094
    ],
    "AL": [
      51.748,
      -0.34
    ],
    "B": [
      52.486,
      -1.89
    ],
    "BA": [
      51.381,
      -2.36
    ],
    "BB": [
      53.748,
      -2.482
    ],
    "BD": [
      53.795,
      -1.759
    ],
    "BH": [
      50.72,
      -1.879
    ],
    "BL": [
      53.577,
      -2.429
    ],
    "BN": [
      50.829,
      -0.137
    ],
    "BR": [
      51.407,
      0.014
    ],
    "BS": [
      51.455,
      -2.587
    ],
    "BT": [
      54.597,
      -5.93
    ],
    "CA": [
      54.894,
      -2.933
    ],
    "CB": [
      52.205,
      0.119
    ],
    "CF": [
      51.481,
      -3.18
    ],
    "CH": [
      53.191,
      -2.891
    ],
    "CM": [
      51.736,
      0.47
    ],
    "CO": [
      51.889,
      0.903
    ],
    "CR": [
      51.372,
      -0.098
    ],
    "CT": [
      51.28,
      1.08
    ],
    "CV": [
      52.408,
      -1.51
    ],
    "CW": [
      53.098,
      -2.441
    ],
    "DA": [
      51.446,
      0.22
    ],
    "DD": [
      56.462,
      -2.97
    ],
    "DE": [
      52.921,
      -1.475
    ],
    "DG": [
      55.071,
      -3.605
    ],
    "DH": [
      54.779,
      -1.559
    ],
    "DL": [
      54.525,
      -1.553
    ],
    "DN": [
      53.523,
      -1.128
    ],
    "DT": [
      50.716,
      -2.439
    ],
    "DY": [
      52.512,
      -2.078
    ],
    "E": [
      51.54,
      -0.06
    ],
    "EC": [
      51.517,
      -0.099
    ],
    "EH": [
      55.953,
      -3.189
    ],
    "EN": [
      51.652,
      -0.085
    ],
    "EX": [
      50.718,
      -3.534
    ],
    "FK": [
      56.002,
      -3.784
    ],
    "FY": [
      53.821,
      -3.036
    ],
    "G": [
      55.865,
      -4.257
    ],
    "GL": [
      51.864,
      -2.238
    ],
    "GU": [
      51.236,
      -0.57
    ],
    "HA": [
      51.58,
      -0.336
    ],
    "HD": [
      53.645,
      -1.785
    ],
    "HG": [
      53.993,
      -1.541
    ],
    "HP": [
      51.753,
      -0.447
    ],
    "HR": [
      52.056,
      -2.716
    ],
    "HS": [
      57.761,
      -7.019
    ],
    "HU": [
      53.745,
      -0.337
    ],
    "HX": [
      53.722,
      -1.864
    ],
    "IG": [
      51.558,
      0.075
    ],
    "IP": [
      52.057,
      1.155
    ],
    "IV": [
      57.477,
      -4.225
    ],
    "JE": [
      49.215,
      -2.131
    ],
    "KA": [
      55.612,
      -4.496
    ],
    "KT": [
      51.41,
      -0.302
    ],
    "KW": [
      58.44,
      -3.09
    ],
    "KY": [
      56.112,
      -3.167
    ],
    "L": [
      53.408,
      -2.991
    ],
    "LA": [
      54.047,
      -2.799
    ],
    "LD": [
      52.244,
      -3.625
    ],
    "LE": [
      52.638,
      -1.131
    ],
    "LL": [
      53.093,
      -3.809
    ],
    "LN": [
      53.234,
      -0.54
    ],
    "LS": [
      53.799,
      -1.549
    ],
    "LU": [
      51.878,
      -0.42
    ],
    "M": [
      53.479,
      -2.245
    ],
    "ME": [
      51.272,
      0.529
    ],
    "MK": [
      52.041,
      -0.759
    ],
    "ML": [
      55.782,
      -3.988
    ],
    "N": [
      51.57,
      -0.11
    ],
    "NE": [
      54.978,
      -1.618
    ],
    "NG": [
      52.954,
      -1.158
    ],
    "NN": [
      52.24,
      -0.903
    ],
    "NP": [
      51.588,
      -2.998
    ],
    "NR": [
      52.628,
      1.299
    ],
    "NW": [
      51.55,
      -0.176
    ],
    "OL": [
      53.541,
      -2.118
    ],
    "OX": [
      51.752,
      -1.258
    ],
    "PA": [
      55.845,
      -4.424
    ],
    "PE": [
      52.573,
      -0.24
    ],
    "PH": [
      56.395,
      -3.437
    ],
    "PL": [
      50.375,
      -4.143
    ],
    "PO": [
      50.799,
      -1.091
    ],
    "PR": [
      53.763,
      -2.702
    ],
    "RG": [
      51.454,
      -0.978
    ],
    "RH": [
      51.237,
      -0.171
    ],
    "RM": [
      51.575,
      0.183
    ],
    "S": [
      53.381,
      -1.47
    ],
    "SA": [
      51.619,
      -3.943
    ],
    "SE": [
      51.49,
      -0.057
    ],
    "SG": [
      51.902,
      -0.198
    ],
    "SK": [
      53.407,
      -2.157
    ],
    "SL": [
      51.511,
      -0.594
    ],
    "SM": [
      51.369,
      -0.192
    ],
    "SN": [
      51.558,
      -1.783
    ],
    "SO": [
      50.909,
      -1.405
    ],
    "SP": [
      51.068,
      -1.796
    ],
    "SR": [
      54.906,
      -1.383
    ],
    "SS": [
      51.546,
      0.707
    ],
    "ST": [
      53.003,
      -2.18
    ],
    "SW": [
      51.464,
      -0.161
    ],
    "SY": [
      52.708,
      -2.752
    ],
    "TA": [
      51.015,
      -3.101
    ],
    "TD": [
      55.614,
      -2.81
    ],
    "TF": [
      52.695,
      -2.449
    ],
    "TN": [
      51.196,
      0.276
    ],
    "TQ": [
      50.462,
      -3.526
    ],
    "TS": [
      54.573,
      -1.234
    ],
    "TW": [
      51.449,
      -0.337
    ],
    "UB": [
      51.514,
      -0.398
    ],
    "W": [
      51.511,
      -0.185
    ],
    "WA": [
      53.39,
      -2.597
    ],
    "WC": [
      51.517,
      -0.12
    ],
    "WD": [
      51.656,
      -0.396
    ],
    "WF": [
      53.683,
      -1.506
    ],
    "WN": [
      53.544,
      -2.631
    ],
    "WR": [
      52.193,
      -2.221
    ],
    "WS": [
      52.586,
      -1.982
    ],
    "WV": [
      52.585,
      -2.128
    ],
    "YO": [
      53.959,
      -1.082
    ],
    "ZE": [
      60.154,
      -1.145
    ]
  },
  "uk": {
    "claimants": {
      "L": {
        "Professional, Scientific & Tech": 2,
        "Hospitality": 2,
        "Other Services": 4,
        "Wholesale & Retail Trade": 1,
        "Unknown / Foreign": 1
      },
      "G": {
        "Information & Communication": 1,
        "Manufacturing": 14,
        "Agriculture, Forestry & Fishing": 9,
        "Other Services": 1,
        "Public Sector": 5,
        "Energy & Water Supply": 1,
        "Wholesale & Retail Trade": 1,
        "Administrative & Support": 1
      },
      "EC": {
        "Real Estate": 6,
        "Transport & Storage": 1,
        "Retail": 3,
        "Manufacturing": 2,
        "Administrative & Support": 1,
        "Unknown / Foreign": 2,
        "Professional, Scientific & Tech": 1,
        "Other Services": 2,
        "Information & Communication": 1,
        "Accommodation & Food Services": 2,
        "Wholesale & Retail Trade": 2
      },
      "AL": {
        "Retail": 6,
        "Professional, Scientific & Tech": 23,
        "Wholesale & Retail Trade": 1,
        "Accommodation & Food Services": 1
      },
      "YO": {
        "Financial & Insurance": 2
      },
      "W": {
        "Accommodation & Food Services": 3,
        "Manufacturing": 9,
        "Professional, Scientific & Tech": 3,
        "Wholesale & Retail Trade": 5,
        "Administrative & Support": 3,
        "Information & Communication": 2,
        "Transport & Storage": 1,
        "Financial & Insurance": 3
      },
      "SE": {
        "Wholesale & Retail Trade": 2,
        "Manufacturing": 1,
        "Transport & Storage": 2
      },
      "B": {
        "Professional, Scientific & Tech": 1,
        "Transport & Storage": 2,
        "Other Services": 2,
        "Real Estate": 1,
        "Wholesale & Retail Trade": 2,
        "Accommodation & Food Services": 2
      },
      "RG": {
        "Energy & Water Supply": 1,
        "Manufacturing": 2,
        "Information & Communication": 1
      },
      "SN": {
        "Energy & Water Supply": 2,
        "Other Services": 1
      },
      "NG": {
        "Wholesale & Retail Trade": 5,
        "Transport & Storage": 1,
        "Manufacturing": 2,
        "Other Services": 2,
        "Professional, Scientific & Tech": 1
      },
      "TW": {
        "Other Services": 6,
        "Administrative & Support": 1,
        "Real Estate": 1,
        "Accommodation & Food Services": 3
      },
      "DE": {
        "Other Services": 1
      },
      "AB": {
        "Agriculture, Forestry & Fishing": 7
      },
      "RM": {
        "Other Services": 1,
        "Transport & Storage": 1
      },
      "WF": {
        "Manufacturing": 4,
        "Wholesale & Retail Trade": 2
      },
      "CV": {
        "Professional, Scientific & Tech": 1,
        "Manufacturing": 2,
        "Wholesale & Retail Trade": 1
      },
      "E": {
        "Information & Communication": 3,
        "Financial & Insurance": 2,
        "Administrative & Support": 1,
        "Unknown / Foreign": 1,
        "Construction": 1
      },
      "CO": {
        "Administrative & Support": 1
      },
      "BA": {
        "Wholesale & Retail Trade": 1,
        "Manufacturing": 1
      },
      "CF": {
        "Real Estate": 1,
        "Wholesale & Retail Trade": 1,
        "Construction": 1
      },
      "EH": {
        "Information & Communication": 1,
        "Public Sector": 4
      },
      "MK": {
        "Professional, Scientific & Tech": 1,
        "Wholesale & Retail Trade": 2
      },
      "SG": {
        "Information & Communication": 1,
        "Manufacturing": 2
      },
      "IP": {
        "Manufacturing": 4
      },
      "GL": {
        "Construction": 3,
        "Other Services": 2
      },
      "DN": {
        "Wholesale & Retail Trade": 3
      },
      "PH": {
        "Professional, Scientific & Tech": 1,
        "Public Sector": 1
      },
      "N": {
        "Professional, Scientific & Tech": 1,
        "Wholesale & Retail Trade": 2,
        "Other Services": 1,
        "Real Estate": 2,
        "Transport & Storage": 1,
        "Information & Communication": 1,
        "Mining & Quarrying": 1
      },
      "BD": {
        "Wholesale & Retail Trade": 3
      },
      "JE": {
        "Unknown / Foreign": 1
      },
      "OL": {
        "Wholesale & Retail Trade": 1,
        "Construction": 1
      },
      "DD": {
        "Public Sector": 3
      },
      "WS": {
        "Wholesale & Retail Trade": 2
      },
      "KA": {
        "Public Sector": 3
      },
      "SW": {
        "Professional, Scientific & Tech": 2,
        "Accommodation & Food Services": 2,
        "Unknown / Foreign": 1,
        "Hospitality": 2,
        "Real Estate": 1,
        "Administrative & Support": 1,
        "Information & Communication": 1,
        "Wholesale & Retail Trade": 1,
        "Other Services": 1
      },
      "WD": {
        "Hospitality": 4,
        "Other Services": 1,
        "Accommodation & Food Services": 2
      },
      "GU": {
        "Financial & Insurance": 2,
        "Manufacturing": 1
      },
      "PA": {
        "Public Sector": 1
      },
      "HG": {
        "Accommodation & Food Services": 2
      },
      "SK": {
        "Professional, Scientific & Tech": 1,
        "Construction": 2,
        "Accommodation & Food Services": 2
      },
      "KY": {
        "Public Sector": 1
      },
      "ME": {
        "Wholesale & Retail Trade": 2
      },
      "NN": {
        "Accommodation & Food Services": 2,
        "Manufacturing": 2
      },
      "CW": {
        "Wholesale & Retail Trade": 1,
        "Administrative & Support": 1,
        "Other Services": 1
      },
      "LE": {
        "Wholesale & Retail Trade": 2,
        "Professional, Scientific & Tech": 2,
        "Information & Communication": 1
      },
      "LU": {
        "Accommodation & Food Services": 2,
        "Wholesale & Retail Trade": 1,
        "Manufacturing": 1
      },
      "SM": {
        "Wholesale & Retail Trade": 1
      },
      "BT": {
        "Manufacturing": 8,
        "Other Services": 1,
        "Wholesale & Retail Trade": 6,
        "Construction": 3,
        "Transport & Storage": 1,
        "Mining & Quarrying": 1,
        "Administrative & Support": 1
      },
      "ML": {
        "Public Sector": 2
      },
      "HX": {
        "Other Services": 1,
        "Unknown / Foreign": 2
      },
      "TD": {
        "Public Sector": 1
      },
      "LS": {
        "Public Sector": 1,
        "Manufacturing": 1,
        "Wholesale & Retail Trade": 2,
        "Retail": 2
      },
      "SL": {
        "Transport & Storage": 1,
        "Professional, Scientific & Tech": 1,
        "Wholesale & Retail Trade": 2,
        "Construction": 1
      },
      "SP": {
        "Other Services": 1
      },
      "KT": {
        "Unknown / Foreign": 2,
        "Administrative & Support": 1,
        "Wholesale & Retail Trade": 4
      },
      "NP": {
        "Other Services": 1
      },
      "SS": {
        "Wholesale & Retail Trade": 1
      },
      "TA": {
        "Energy & Water Supply": 1
      },
      "SO": {
        "Transport & Storage": 1,
        "Energy & Water Supply": 1
      },
      "WA": {
        "Professional, Scientific & Tech": 1,
        "Wholesale & Retail Trade": 1,
        "Unknown / Foreign": 2
      },
      "RH": {
        "Unknown / Foreign": 1
      },
      "NW": {
        "Professional, Scientific & Tech": 1
      },
      "TN": {
        "Wholesale & Retail Trade": 1
      },
      "M": {
        "Administrative & Support": 2,
        "Unknown / Foreign": 1,
        "Wholesale & Retail Trade": 1
      },
      "FY": {
        "Unknown / Foreign": 2,
        "Professional, Scientific & Tech": 1
      },
      "HU": {
        "Other Services": 2
      },
      "BR": {
        "Professional, Scientific & Tech": 1,
        "Manufacturing": 2
      },
      "WC": {
        "Energy & Water Supply": 1,
        "Accommodation & Food Services": 4,
        "Other Services": 2
      },
      "BH": {
        "Wholesale & Retail Trade": 2
      },
      "BL": {
        "Financial & Insurance": 1,
        "Wholesale & Retail Trade": 1
      },
      "PO": {
        "Other Services": 2
      },
      "DA": {
        "Construction": 1
      },
      "HP": {
        "Accommodation & Food Services": 1
      },
      "FK": {
        "Agriculture, Forestry & Fishing": 1,
        "Manufacturing": 2
      },
      "ST": {
        "Other Services": 1,
        "Administrative & Support": 1
      },
      "UB": {
        "Wholesale & Retail Trade": 1
      },
      "DT": {
        "Wholesale & Retail Trade": 1
      }
    },
    "defendants": {
      "CF": {
        "Professional, Scientific & Tech": 6,
        "Accommodation & Food Services": 12,
        "Wholesale & Retail Trade": 10,
        "Other Services": 5,
        "Administrative & Support": 2,
        "Manufacturing": 6,
        "Agriculture, Forestry & Fishing": 2,
        "Unknown / Foreign": 6,
        "Hospitality": 3,
        "Financial & Insurance": 3,
        "Retail": 4,
        "Real Estate": 1,
        "Transport & Storage": 1,
        "Construction": 1
      },
      "EH": {
        "Information & Communication": 1
      },
      "OX": {
        "Real Estate": 1,
        "Transport & Storage": 2,
        "Information & Communication": 1,
        "Professional, Scientific & Tech": 1,
        "Manufacturing": 3,
        "Construction": 2,
        "Administrative & Support": 4,
        "Wholesale & Retail Trade": 6,
        "Other Services": 2,
        "Mining & Quarrying": 1
      },
      "MK": {
        "Retail": 6
      },
      "DA": {
        "Other Services": 1
      },
      "ST": {
        "Financial & Insurance": 1
      },
      "RG": {
        "Unknown / Foreign": 1
      },
      "WA": {
        "Professional, Scientific & Tech": 3,
        "Manufacturing": 3,
        "Agriculture, Forestry & Fishing": 2,
        "Energy & Water Supply": 1
      },
      "AL": {
        "Professional, Scientific & Tech": 3,
        "Other Services": 1,
        "Manufacturing": 3,
        "Agriculture, Forestry & Fishing": 2,
        "Real Estate": 1,
        "Wholesale & Retail Trade": 1
      },
      "CB": {
        "Other Services": 1
      },
      "SK": {
        "Professional, Scientific & Tech": 6,
        "Other Services": 2,
        "Manufacturing": 6,
        "Agriculture, Forestry & Fishing": 4,
        "Information & Communication": 1,
        "Wholesale & Retail Trade": 1
      },
      "DE": {
        "Professional, Scientific & Tech": 3,
        "Other Services": 1,
        "Manufacturing": 3,
        "Agriculture, Forestry & Fishing": 2
      },
      "DN": {
        "Transport & Storage": 2,
        "Professional, Scientific & Tech": 1
      },
      "SL": {
        "Manufacturing": 4,
        "Professional, Scientific & Tech": 1,
        "Unknown / Foreign": 1,
        "Wholesale & Retail Trade": 1
      },
      "L": {
        "Professional, Scientific & Tech": 1
      },
      "M": {
        "Manufacturing": 1,
        "Other Services": 1
      },
      "NW": {
        "Administrative & Support": 1
      },
      "BN": {
        "Wholesale & Retail Trade": 1,
        "Other Services": 1
      },
      "SE": {
        "Information & Communication": 1,
        "Professional, Scientific & Tech": 3,
        "Other Services": 1
      },
      "SS": {
        "Transport & Storage": 2,
        "Wholesale & Retail Trade": 2,
        "Construction": 2,
        "Agriculture, Forestry & Fishing": 1,
        "Manufacturing": 2,
        "Public Sector": 1
      },
      "EC": {
        "Information & Communication": 3,
        "Manufacturing": 6,
        "Wholesale & Retail Trade": 12,
        "Professional, Scientific & Tech": 4,
        "Transport & Storage": 1,
        "Energy & Water Supply": 2,
        "Unknown / Foreign": 4,
        "Real Estate": 2,
        "Other Services": 4,
        "Construction": 3,
        "Financial & Insurance": 1,
        "Accommodation & Food Services": 2,
        "Administrative & Support": 3
      },
      "SO": {
        "Other Services": 1,
        "Professional, Scientific & Tech": 1,
        "Real Estate": 1,
        "Energy & Water Supply": 1
      },
      "W": {
        "Professional, Scientific & Tech": 4,
        "Unknown / Foreign": 2,
        "Wholesale & Retail Trade": 9,
        "Hospitality": 2,
        "Financial & Insurance": 2,
        "Other Services": 3,
        "Accommodation & Food Services": 3,
        "Manufacturing": 4,
        "Transport & Storage": 1,
        "Administrative & Support": 1,
        "Retail": 2
      },
      "WD": {
        "Other Services": 1
      },
      "NN": {
        "Wholesale & Retail Trade": 1
      },
      "UB": {
        "Wholesale & Retail Trade": 1
      },
      "G": {
        "Public Sector": 25,
        "Energy & Water Supply": 1
      },
      "CV": {
        "Wholesale & Retail Trade": 1,
        "Manufacturing": 1,
        "Unknown / Foreign": 1
      },
      "EN": {
        "Wholesale & Retail Trade": 1
      },
      "LS": {
        "Manufacturing": 1
      },
      "NE": {
        "Wholesale & Retail Trade": 3
      },
      "WC": {
        "Administrative & Support": 1,
        "Manufacturing": 1,
        "Wholesale & Retail Trade": 1,
        "Real Estate": 1,
        "Information & Communication": 4,
        "Unknown / Foreign": 1,
        "Professional, Scientific & Tech": 1
      },
      "E": {
        "Unknown / Foreign": 7,
        "Professional, Scientific & Tech": 1,
        "Manufacturing": 2,
        "Construction": 2,
        "Administrative & Support": 2,
        "Wholesale & Retail Trade": 10,
        "Accommodation & Food Services": 10,
        "Information & Communication": 1,
        "Real Estate": 4,
        "Other Services": 8,
        "Hospitality": 3,
        "Financial & Insurance": 2,
        "Transport & Storage": 1,
        "Mining & Quarrying": 1
      },
      "BL": {
        "Wholesale & Retail Trade": 1
      },
      "SP": {
        "Other Services": 1,
        "Professional, Scientific & Tech": 2,
        "Manufacturing": 3,
        "Agriculture, Forestry & Fishing": 2
      },
      "B": {
        "Manufacturing": 5,
        "Agriculture, Forestry & Fishing": 1
      },
      "SW": {
        "Manufacturing": 4,
        "Agriculture, Forestry & Fishing": 1,
        "Other Services": 1,
        "Wholesale & Retail Trade": 3,
        "Unknown / Foreign": 1,
        "Financial & Insurance": 1,
        "Construction": 1,
        "Transport & Storage": 1,
        "Professional, Scientific & Tech": 2,
        "Retail": 2
      },
      "GL": {
        "Transport & Storage": 1,
        "Other Services": 1
      },
      "N": {
        "Other Services": 1,
        "Construction": 2,
        "Unknown / Foreign": 1,
        "Manufacturing": 1
      },
      "JE": {
        "Information & Communication": 1,
        "Professional, Scientific & Tech": 1
      },
      "RM": {
        "Administrative & Support": 1
      },
      "BB": {
        "Wholesale & Retail Trade": 1
      },
      "BD": {
        "Retail": 1
      },
      "SG": {
        "Accommodation & Food Services": 1
      }
    }
  },
  "international": {
    "claimants": {
      "Unknown / Foreign": 3
    },
    "defendants": {
      "Energy & Water Supply": 2,
      "Wholesale & Retail Trade": 1,
      "Professional, Scientific & Tech": 1
    }
  }
};
